# Generated by Django 4.1.7 on 2023-06-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=32, verbose_name='post title')),
                ('content', models.TextField(blank=True, default='', max_length=1024, verbose_name='post content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='post create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='post update date')),
                ('published_at', models.DateTimeField(verbose_name='post publish date')),
                ('status', models.CharField(blank=True, choices=[('unpublished', 'unpublished'), ('published', 'published'), ('published_and_send', 'published_and_send')], default='unpublished', max_length=32, verbose_name='post status')),
                ('image_b', models.ImageField(upload_to='post_images/', verbose_name='post big image')),
                ('image_s', models.ImageField(upload_to='post_images/', verbose_name='post small image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='post author')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
